---
name: Validate Vale rules

on:
  pull_request:
    paths:
      - .vale/styles/**/*
      - .vale/fixtures/**/*

jobs:
  validate-rules:
    name: Validate rules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install Vale and validate rules
        run: |
          sudo gem install asciidoctor
          wget https://github.com/errata-ai/vale/releases/download/v3.6.0/vale_3.6.0_Linux_64-bit.tar.gz
          mkdir bin && tar -xvzf *Linux_64-bit.tar.gz -C bin
          export PATH=./bin:"$PATH"
          vale -v
          chmod +x tools/validate-vale-rules.sh
          ./tools/validate-vale-rules.sh
